# In _config.yml
title: Bio-Image Analysis with Napari and Python (DIGS-BB Light Microscopy Course 2022)

author: Marcelo Zoccoler and Johannes Müller
logo: biapol_logo.png
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/BiAPoL/DIGS-BB_LM_Course_Bio-Image_Analysis_2022
html:
  use_repository_button: true
